Add mutations for v2 ManageBoxes
boxwise/boxtribute pull request #1375
Opened 2024-06-11 11:58 UTC by pylipp

- Add Box.deletedOn field in GraphQL API
- Add mutation to bulk-delete boxes

2024-06-11 12:00 UTC, pylipp commented
![](https://github.trello.services/images/mini-trello-icon.png) [2.0 Add mutations for ManageBoxes](https://trello.com/c/qBxxUS2s/1418-20-add-mutations-for-manageboxes)

2024-06-17 14:43 UTC, HaGuesto requested changes
add in new PR/ticket validation for deleted boxes in other box mutation

2024-06-17 14:43 UTC, HaGuesto commented on back/boxtribute_server/business_logic/warehouse/box/mutations.py
> +            Box.location != location_id,
please filter out deleted boxes

2024-06-17 14:43 UTC, HaGuesto commented on back/boxtribute_server/graph_ql/definitions/protected/types.graphql
> +union MoveBoxesResult = BoxPage | InsufficientPermissionError | ResourceDoesNotExistError | UnauthorizedForBaseError
change BoxPage type so that it also includes an array of failedLabelIdentifiers

2024-06-17 14:43 UTC, HaGuesto commented on back/boxtribute_server/business_logic/warehouse/box/mutations.py
> +            Box.label_identifier << update_input["label_identifiers"],
filter for deleted boxes

2024-06-17 14:43 UTC, HaGuesto commented on back/boxtribute_server/business_logic/warehouse/box/mutations.py
> +            on=(
filter for deleted boxes

2024-06-17 14:43 UTC, HaGuesto commented on back/boxtribute_server/business_logic/warehouse/box/crud.py
> +            TagsRelation.tag == tag.id,
this would unassign this tag from all boxes

2024-06-17 14:43 UTC, HaGuesto commented on back/boxtribute_server/business_logic/statistics/crud.py
> +        .where(Box.deleted_on.is_null())
((Box.deleted_on == 0) | (Box.deleted_on.is_null()))

2024-06-17 14:55 UTC, HaGuesto commented
> 1. How do you like the handling of non-existing boxes/unauthorized boxes (they're being ignored)
I want to know at least which labelIdentifiers were ignored.
> 2. How do handle deleted locations or tags? Should there be an error if the user tries to move boxes to a deleted location, or assign a deleted tag to boxes?
it should neither be possible to move boxes to deleted locations nor assign deleted tags. Please create an error for each case.

> 3. Should we validate that the location that boxes should be moved to is in the same base as the boxes currently are?
Yes

2024-06-20 19:25 UTC, HaGuesto commented
# Functional review
- when running the boxes query only non-deleted boxes are returned and there is no filter 
--> why do we have a deletedOn field then for the boxes query?

- deleteBoxes works as expected
- moveBoxesToLocation works as expected.
- unassignTagFromBoxes works as expected.
- assignTagToBoxes does not work for me for both tagIds that were already assigned to the box or not. It seems like the unique index is failing. In both cases I get the following error:

```

mutation {
  assignTagToBoxes(
    updateInput: {labelIdentifiers: ["62794655" ], tagId: 56 }
  ) {
    ... on BoxResult {
      updatedBoxes {
        id
        state
        deletedOn
        location {
          id
          name
        }
        tags {
          id
          name
        }
      }
      invalidBoxLabelIdentifiers
    }
    ... on InsufficientPermissionError {
      __typename
      name
    }
    ... on ResourceDoesNotExistError {
      __typename
      name
    }
    ... on UnauthorizedForBaseError {
      __typename
      name
    }
    ... on TagTypeMismatchError {
      __typename
    }
        ... on DeletedTagError {
      __typename
      name
    }
    
  }
}



webapp-1  | GraphQL request:2:3
webapp-1  | 1 | mutation {
webapp-1  | 2 |   assignTagToBoxes(
webapp-1  |   |   ^
webapp-1  | 3 |     updateInput: {labelIdentifiers: ["62794655" ], tagId: 56 }
webapp-1  | Traceback (most recent call last):
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3311, in execute_sql
webapp-1  |     cursor.execute(sql, params or ())
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
webapp-1  |     result = self._query(query)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
webapp-1  |     conn.query(q)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
webapp-1  |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
webapp-1  |     result.read()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
webapp-1  |     first_packet = self.connection._read_packet()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
webapp-1  |     packet.raise_for_error()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
webapp-1  |     err.raise_mysql_exception(self._data)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
webapp-1  |     raise errorclass(errno, errval)
webapp-1  | pymysql.err.IntegrityError: (1062, "Duplicate entry '100000249-56-Stock' for key 'tags_relations.PRIMARY'")
webapp-1  | 
webapp-1  | During handling of the above exception, another exception occurred:
webapp-1  | 
webapp-1  | Traceback (most recent call last):
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/graphql/execution/execute.py", line 521, in execute_field
webapp-1  |     result = resolve_fn(source, info, **args)
webapp-1  |   File "/app/back/boxtribute_server/authz.py", line 64, in inner
webapp-1  |     return f(*args, **kwargs)
webapp-1  |   File "/app/back/boxtribute_server/business_logic/warehouse/box/mutations.py", line 190, in resolve_assign_tag_to_boxes
webapp-1  |     updated_boxes=assign_tag_to_boxes(user_id=g.user.id, boxes=boxes, tag=tag),
webapp-1  |   File "/app/back/boxtribute_server/business_logic/warehouse/box/crud.py", line 322, in assign_tag_to_boxes
webapp-1  |     TagsRelation.bulk_create(tags_relations, batch_size=BATCH_SIZE)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6762, in bulk_create
webapp-1  |     res = cls.insert_many(accum, fields=fields).execute()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2025, in inner
webapp-1  |     return method(self, database, *args, **kwargs)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2096, in execute
webapp-1  |     return self._execute(database)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2901, in _execute
webapp-1  |     return super(Insert, self)._execute(database)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2614, in _execute
webapp-1  |     cursor = database.execute(self)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3319, in execute
webapp-1  |     return self.execute_sql(sql, params)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3309, in execute_sql
webapp-1  |     with __exception_wrapper__:
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3077, in __exit__
webapp-1  |     reraise(new_type, new_type(exc_value, *exc_args), traceback)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 196, in reraise
webapp-1  |     raise value.with_traceback(tb)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 3311, in execute_sql
webapp-1  |     cursor.execute(sql, params or ())
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
webapp-1  |     result = self._query(query)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
webapp-1  |     conn.query(q)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
webapp-1  |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
webapp-1  |     result.read()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
webapp-1  |     first_packet = self.connection._read_packet()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
webapp-1  |     packet.raise_for_error()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
webapp-1  |     err.raise_mysql_exception(self._data)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
webapp-1  |     raise errorclass(errno, errval)
webapp-1  | peewee.IntegrityError: (1062, "Duplicate entry '100000249-56-Stock' for key 'tags_relations.PRIMARY'")
webapp-1  | 
webapp-1  | The above exception was the direct cause of the following exception:
webapp-1  | 
webapp-1  | Traceback (most recent call last):
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/graphql/execution/execute.py", line 521, in execute_field
webapp-1  |     result = resolve_fn(source, info, **args)
webapp-1  |   File "/app/back/boxtribute_server/authz.py", line 64, in inner
webapp-1  |     return f(*args, **kwargs)
webapp-1  |   File "/app/back/boxtribute_server/business_logic/warehouse/box/mutations.py", line 190, in resolve_assign_tag_to_boxes
webapp-1  |     updated_boxes=assign_tag_to_boxes(user_id=g.user.id, boxes=boxes, tag=tag),
webapp-1  |   File "/app/back/boxtribute_server/business_logic/warehouse/box/crud.py", line 322, in assign_tag_to_boxes
webapp-1  |     TagsRelation.bulk_create(tags_relations, batch_size=BATCH_SIZE)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 6762, in bulk_create
webapp-1  |     res = cls.insert_many(accum, fields=fields).execute()
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2025, in inner
webapp-1  |     return method(self, database, *args, **kwargs)
webapp-1  |   File "/usr/local/lib/python3.10/site-packages/peewee.py", line 2096, in execute
web [...]

2024-06-24 18:23 UTC, pylipp commented
> * assignTagToBoxes does not work for me for both tagIds that were already assigned to the box or not. It seems like the unique index is failing.

There was an error in the filtering logic for boxes that have multiple tags assigned already, it's fixed now in [cca8ca5](https://github.com/boxwise/boxtribute/pull/1375/commits/cca8ca5c0238f374839bc146a3ca322bd15471d6). @HaGuesto good catch :muscle:

2024-06-25 10:22 UTC, merged