Add tooltip for Age column
boxwise/boxtribute pull request #1887
Opened 2024-12-30 11:19 UTC by jlin95

2024-12-30 13:14 UTC, pylipp approved these changes
![2024-12-30-141003_1366x768_scrot](https://github.com/user-attachments/assets/63a58b75-1ac7-4f8a-b25a-ea3b6b728fc2)


**Functional review passes**. 
@aerinsol added screenshot for you

2024-12-30 13:18 UTC, pylipp commented
@jlin95 can you try linking this PR from the Trello card via the Github power-up?

2024-12-30 15:02 UTC, aerinsol requested changes
Needs some sort of info or tappable icon on mobile. Mouseover on header is not sufficient.

2025-01-03 10:53 UTC, pylipp commented
![2025-01-03-115138_1097x275_scrot](https://github.com/user-attachments/assets/e8757e8d-27fc-4f78-8e5b-d9c443385c06)

@jlin95 I'm afraid the text needs linebreaks or some kind of wrapping because it currently overflows.
@aerinsol any chance we can shorten the text?

2025-01-03 13:02 UTC, aerinsol commented
Still needs an info icon

2025-01-03 22:51 UTC, pylipp commented
> Still needs an info icon

There's an info icon next to the AGE column title, would you like it to be positioned elsewhere?

2025-01-05 23:54 UTC, jlin95 commented
@aerinsol Maybe the other way is to add the disclaimer text above the table when in mobile view? And perhaps shorten the age explanation...

2025-01-19 23:12 UTC, jlin95 commented
Fixed the popover content overflowing issue based on this: https://github.com/chakra-ui/chakra-ui/issues/2609.
@aerinsol / @pylipp for review.

2025-01-20 21:35 UTC, jlin95 commented
<img width="1512" alt="Screenshot 2025-01-20 at 22 30 23" src="https://github.com/user-attachments/assets/8a9afb32-fb1c-4684-ae8f-87f31a031687" />

cc @pylipp

2025-01-21 09:28 UTC, aerinsol commented
@jlin95 not super happy with this. Is it possible to just make the first review version work on mobile?

2025-01-21 10:41 UTC, pylipp commented
@aerinsol could you come to an accommodation in terms of requirements on this one? E.g. a shorter text would make be easier to fit on any screen while also keeping a clean look (see screenshots below). The info icon is clearly visible next to the AGE text, and tappable on mobile.
Please bear in mind that this PR has been open for 3 weeks now with several iterations but was originally labeled as tiny task :sweat_smile: 
![2025-01-21-113546_1265x417_scrot](https://github.com/user-attachments/assets/e309502a-6c6b-4297-9db1-b8b20eead479)
![2025-01-21-113431_439x584_scrot](https://github.com/user-attachments/assets/83a6d7c5-5766-42fe-8602-312f1a7ace2a)

2025-01-21 13:22 UTC, aerinsol commented
Ok, that's a fair comment @pylipp ;)

Sometimes like everyone I can get carried away with wanting things to JUST WORK.

Yes, keeping just the first sentence is an acceptable solution in light of that. Will approve with the suggested edits.

2025-01-21 15:16 UTC, pylipp commented
@aerinsol thanks, feels good to move forward! 
@jlin95 I created the screenshots with this modification using the chakra Text component
```js
<PopoverBody>
  <Text>How old the box is from the time<br />it was first created in Boxtribute.</Text>
</PopoverBody>
```

2025-01-22 08:44 UTC, jlin95 commented
@pylipp done!

2025-01-22 13:54 UTC, merged