BoxEdit: Add Colors to the Tag Options
boxwise/boxtribute pull request #577
Opened 2023-01-02 15:32 UTC by vahidbazzaz

2023-01-02 15:37 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [2.0 BoxEdit: give tags color](https://trello.com/c/2McAE5b1)

2023-01-02 16:02 UTC, pylipp requested changes
Code review and functional review done, two remarks in comments :)

2023-01-02 21:48 UTC, vahidbazzaz commented on react/src/components/Form/SelectField.tsx
> +                background: state.data?.color || "gray.100",
@pylipp That makes total sense, as the user just selects the background color, then we adjust the font color using contrast ratio math. I'll push the changes.

2023-01-02 21:51 UTC, vahidbazzaz commented on react/src/components/Form/SelectField.tsx
>                  border: "1px",
@pylipp If the background color is so bright, a border with higher contrast would make sense. I will push the changes, and you can try them out.

2023-01-03 14:25 UTC, pylipp commented on react/src/utils/helpers.ts
> +export const getContrastYIQ = (hex) => {
Can you add a comment, e.g.
Return true if given RGB hex color is bright, false if dark.
This is achieved by converting the RGB value into YIQ and then checking the Y component (luma). Cf. https://stackoverflow.com/a/946734/3865876

2023-01-03 14:25 UTC, pylipp commented on react/src/utils/helpers.ts
> +export const getContrastYIQ = (hex) => {
Maybe the function name `colorIsBright` would suit better then?

2023-01-03 14:27 UTC, pylipp commented on react/src/views/BoxCreate/components/BoxCreate.tsx
> +    color: tag.color,
Good catch :+1:

2023-01-03 14:27 UTC, pylipp approved these changes
Works and brings UX enhancements, nice! :tada:

2023-01-03 14:40 UTC, merged