Display Toast Message Bottom on Mobile
boxwise/boxtribute pull request #593
Opened 2023-01-15 07:13 UTC by vahidbazzaz

2023-01-15 11:37 UTC, pylipp requested changes
@vahidbazzaz I tested it on a 1366px screen and the toast still shows at the bottom, how did you test it?

Anyways I think we shouldn't spend that much more time since the task is not prioritized.

2023-01-15 14:10 UTC, vahidbazzaz commented
> @vahidbazzaz I tested it on a 1366px screen and the toast still shows at the bottom, how did you test it?
> 
> Anyways I think we shouldn't spend that much more time since the task is not prioritized.

@pylipp Thanks for checking that. I have checked it again and it seems to be working fine. If the screen size exceeds 1070px, the toast will appear at the top. Would you mind checking it out again when you have time?

2023-01-19 10:23 UTC, aerinsol commented
@vahidbazzaz @HaGuesto @vahidbazzaz this feature is now live, did it get replaced by a different PR?

2023-01-19 11:46 UTC, vahidbazzaz commented
> @vahidbazzaz @HaGuesto @vahidbazzaz this feature is now live, did it get replaced by a different PR?

@aerinsol This PR adds toast to the top on desktop, and to the bottom when below 1070 pixels. It complements Hans's previous [PR](https://github.com/boxwise/boxtribute/pull/591) that put all toast messages at the bottom. However, since this PR is not urgent, it has not been merged yet. Also needs to be reviewed.

2023-02-02 13:23 UTC, pylipp commented on react/src/utils/hooks.ts
> +        position: position,
I rebased on latest master and the project does not build anymore. In this line I get an eslint complaint `Expected property shorthand  object-shorthand`

2023-02-02 13:25 UTC, pylipp commented
> To test, please follow these instructions:
> 
> Open the box view on a large screen (wider than 1070px) and click the Scrap or Lost button. The notification should appear on top. If you follow the same steps on a smaller screen or on a mobile device, you should see notification at the bottom of the screen

I can confirm that it works functionally, just an eslint complaint to be resolved after rebasing on master.

2023-02-03 09:27 UTC, HaGuesto commented
@pylipp I fixed the eslint error. Ready to merge.

2023-02-03 14:39 UTC, pylipp approved these changes

2023-02-03 14:49 UTC, merged