Fix/add qr and agreements to db seed
boxwise/boxtribute pull request #634
Opened 2023-01-31 07:18 UTC by HaGuesto

2023-01-31 07:19 UTC, HaGuesto commented
![](https://github.trello.services/images/mini-trello-icon.png) [align db seed of dropapp and v2. Qr-Codes pictures in the repo are not in the db seed in the new app #sprint-jan-30](https://trello.com/c/kyxhpmHm/1067-align-db-seed-of-dropapp-and-v2-qr-codes-pictures-in-the-repo-are-not-in-the-db-seed-in-the-new-app-sprint-jan-30)

2023-01-31 09:51 UTC, pylipp commented on back/init.sql
> +INSERT INTO `transfer_agreement` VALUES (1,1,2,'UnderReview','Bidirectional','2023-01-24 07:25:25',8,NULL,NULL,NULL,NULL,'2023-01-24 07:25:25',NULL,NULL),(2,2,1,'UnderReview','Bidirectional','2023-01
The value `Unidirectional` does not exist anymore. For ID 3 it should be `SendingTo`, for ID 4 `ReceivingFrom`

2023-01-31 09:55 UTC, pylipp requested changes
In `back/test/conftest.py` is a line with `setup_box_transfer_models()` which was used to insert transfer models into the dropapp_dev database in the context of integration testing. There now is an error because the seed already contains agreements. So I think the line can be removed. But even then I expect errors in other integration tests that rely on QR codes and box label identifiers from the seed.

2023-01-31 09:57 UTC, pylipp commented on back/init.sql
> +INSERT INTO `transfer_agreement` VALUES (1,1,2,'UnderReview','Bidirectional','2023-01-24 07:25:25',8,NULL,NULL,NULL,NULL,'2023-01-24 07:25:25',NULL,NULL),(2,2,1,'UnderReview','Bidirectional','2023-01
Can you rebase on latest master?

2023-01-31 10:19 UTC, pylipp commented
@HaGuesto Also I'd like to understand how these new values were generated and whether one must be careful in the future when creating a dump from the staging DB and using it as the seed for the dev DB.

2023-02-09 19:32 UTC, HaGuesto commented
@pylipp This is ready to review again.

2023-02-10 04:35 UTC, HaGuesto commented on back/test/integration_tests/test_permissions.py
> +            [ATHENS_ID],
@pylipp I just realized that in other PRs these tests fail, too. This fix should solve it. 
The problem is that another_dev_coordinatorr and another_dev_volunteer are associated with base Athens in the db seed, but with base Thessaloniki in Auth0. 
I fixed this and synced it.

2023-02-10 12:07 UTC, pylipp approved these changes

2023-02-10 12:07 UTC, merged