BoxView: Hide Trasnfer Tab If There Is No Shipment in a Preparing State Available
boxwise/boxtribute pull request #982
Opened 2023-08-24 09:15 UTC by vahidbazzaz

- remove the transfer tab as a temporary workaround
- update test case 4.6.1.3 and add new test case 4.6.1.3b

2023-08-24 09:17 UTC, vahidbazzaz commented
![](https://github.trello.services/images/mini-trello-icon.png) [2.0 Hide tab of Shipments in BoxView if there is no shipment a in Preparing state available](https://trello.com/c/4lxf6jY3/1255-20-hide-tab-of-shipments-in-boxview-if-there-is-no-shipment-a-in-preparing-state-available)

2023-08-24 12:17 UTC, pylipp requested changes
## Functional review
It does not work as expected:
I logged in as dev_coordinator@boxaid.org. On the shipments page I can see that e.g. shipment 1 is in preparing state (BoxAid -> BoxCare). I go to `http://localhost:3000/bases/1/boxes/5881054` which is an InStock box in the Stockroom location. I click the transfers tab but it is empty. I expect that I can select shipment 1. Same e.g. with `http://localhost:3000/bases/1/boxes/8105932`

2023-08-24 13:53 UTC, vahidbazzaz commented
> [Aug 24, 2023 ](#pullrequestreview-1593454408)
> [ View reviewed changes ](/boxwise/boxtribute/pull/982/files/705bf212e9a2a463abe0115ecb1b4b3e5e1076a9)

@pylipp I've fixed the issue, could you please check it again. Thanks.

2023-08-25 12:57 UTC, pylipp approved these changes

2023-08-25 12:57 UTC, merged